import type { Rect } from './math.js';

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/** Stable per-connection id, generated by the server. Never supplied by clients. */
export type PlayerId = string;
export type EntityId = number;

/**
 * A `Clan` is a persistent social group (implemented in a later milestone).
 * A `Team` only exists for the duration of one match. Keeping them separate in
 * the data model now means clan support does not require a schema rewrite.
 */
export interface ClanRef {
  clanId: string;
  tag: string;
  name: string;
}

export interface PlayerProfile {
  playerId: PlayerId;
  displayName: string;
  guest: boolean;
  clan?: ClanRef;
}

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export const TEAM_PRESETS = [
  { name: 'Amber Union', color: '#ffb020', accent: '#7a4d00', symbol: '◆' },
  { name: 'Cobalt Syndicate', color: '#3d8bff', accent: '#0b2f66', symbol: '▲' },
  { name: 'Verdant Cartel', color: '#3ad07a', accent: '#0d4a2a', symbol: '●' },
  { name: 'Crimson Order', color: '#ff4d5e', accent: '#66101a', symbol: '■' },
] as const;

export type TeamIndex = 0 | 1 | 2 | 3;

/** Sentinel team for free-for-all modes, where every player is their own side. */
export const NO_TEAM = -1;

// ---------------------------------------------------------------------------
// Weapons
// ---------------------------------------------------------------------------

export type WeaponId =
  | 'fists'
  | 'sentry'
  | 'mine'
  | 'pipe'
  | 'pistol'
  | 'smg'
  | 'shotgun'
  | 'rifle'
  | 'marksman'
  | 'grenade'
  | 'launcher';

export type WeaponClass = 'melee' | 'sidearm' | 'primary' | 'heavy' | 'throwable';

/** Weapon tiers keep randomised loadouts fair - we randomise *within* a tier. */
export type WeaponTier = 0 | 1 | 2 | 3;

export interface WeaponDef {
  id: WeaponId;
  name: string;
  class: WeaponClass;
  tier: WeaponTier;
  /** Damage per bullet / pellet at point blank. */
  damage: number;
  /** Rounds per minute. */
  rpm: number;
  /** Max effective distance in world units; damage falls off past `falloffStart`. */
  range: number;
  falloffStart: number;
  /** Minimum damage multiplier at max range. */
  falloffMin: number;
  /** Pellets fired per trigger pull (shotguns > 1). */
  pellets: number;
  /** Cone half-angle in radians applied to each pellet. */
  spread: number;
  /** Extra spread accumulated per shot, decaying while not firing. */
  spreadPerShot: number;
  maxSpread: number;
  magazine: number;
  reserveMax: number;
  reloadMs: number;
  /** 0 = hitscan. > 0 spawns a travelling projectile at this speed. */
  projectileSpeed: number;
  /** Radius of the explosion, 0 for non-explosive. */
  explosionRadius: number;
  /** Multiplier applied to player move speed while held. */
  moveMultiplier: number;
  /** Ammo granted by one ammo pickup of this weapon's family. */
  pickupAmmo: number;
  /** Relative weighting when this weapon is chosen for a random spawn. */
  rarity: number;
  /** Extra multiplier on explosive damage to vehicles (mines are built for it). */
  vehicleDamageMult?: number;
  /** Rendering / audio hints - kept in data so assets stay swappable. */
  color: string;
  sfx: string;
}

export interface WeaponState {
  id: WeaponId;
  ammo: number;
  reserve: number;
}

// ---------------------------------------------------------------------------
// Vehicles
// ---------------------------------------------------------------------------

/**
 * Vehicle categories. Each is a distinct role rather than a size variant:
 * the roster is built so there is always a reason to take one over another.
 */
export type VehicleTypeId =
  | 'motorcycle' | 'car' | 'sports' | 'van' | 'truck' | 'armored';

export interface VehicleDef {
  id: VehicleTypeId;
  /** Category shown to players, e.g. "Motorcycle". */
  category: string;
  /** Model name, shown alongside the category. */
  name: string;
  /** Body size in world units (length along facing x width). */
  length: number;
  width: number;
  maxSpeed: number;
  reverseSpeed: number;
  acceleration: number;
  braking: number;
  /** Passive deceleration when no throttle is applied. */
  drag: number;
  /** Max steering rate in radians/sec at low speed. */
  steering: number;
  /** How much steering authority is retained at top speed (0..1). */
  steeringAtSpeed: number;
  /** Lateral velocity retained per second - lower means more grip. */
  grip: number;
  durability: number;
  mass: number;
  seats: number;
  /** Damage dealt to a struck player per unit of impact speed. */
  ramDamage: number;
  /** Camera zoom-out applied while driving this vehicle. */
  cameraZoom: number;
  /** Multiplier on bullet damage the body takes (armour plating lowers it). */
  bulletDamageMult: number;
  /** Multiplier on explosive damage the body takes. */
  explosiveDamageMult: number;
  /**
   * Whether the bodywork stops bullets reaching the occupants. False for a
   * motorcycle: its riders are fully exposed, which is the price of its speed.
   */
  shieldsOccupants: boolean;
  /** Multiplier on damage dealt to barricades and other defences when rammed. */
  demolition: number;
  /** Seats sit one behind another (motorcycle) rather than side by side. */
  inlineSeats?: boolean;
  /**
   * Multiplier on damage from the vehicle's own impacts with walls and other
   * vehicles. A motorcycle is fragile under gunfire, but clipping a kerb should
   * not destroy it.
   */
  crashDamageMult: number;
  /** Strength of the explosion when destroyed; 0 means it breaks rather than blows up. */
  wreckBlast: number;
  /** With nobody aboard it falls over and stops instead of coasting on. */
  topplesWhenRiderless?: boolean;
  /** Short strengths and weaknesses for the HUD vehicle card. */
  pros: string[];
  cons: string[];
  color: string;
}

// ---------------------------------------------------------------------------
// Base defences
// ---------------------------------------------------------------------------

/**
 * Deployables a player can place to fortify their team's base. They are
 * team-owned, destructible, and capped per team so a base cannot be walled off
 * completely.
 */
export type DeployableKind = 'barricade' | 'turret' | 'mine';

export interface DeployableDef {
  kind: DeployableKind;
  name: string;
  /** One line for the HUD, saying what it is for. */
  description: string;
  hp: number;
  /**
   * Footprint in world units. `length` runs along the placement rotation, so a
   * barricade's long wall follows whatever angle it was placed at.
   */
  length: number;
  width: number;
  /** Registers collision: blocks movement and bullets. Mines do not. */
  blocks: boolean;
  /** The player may rotate it during placement. */
  rotatable: boolean;
  /** How many a single team may have standing at once. */
  teamLimit: number;
  /** Seconds before the same player may deploy this again. */
  cooldownSec: number;
  /** Distance in front of the player the deployable is placed. */
  placeOffset: number;
  /** Turret only: engagement envelope and rate of fire. */
  range?: number;
  rpm?: number;
  damage?: number;
  /** Radians per second the barrel can traverse. */
  turnRate?: number;
  /** Seconds after placement before it becomes active. */
  armingSec?: number;
  /** Mine only: distance at which an enemy sets it off. */
  triggerRadius?: number;
  /** Enemies only learn a hidden defence exists inside this distance. */
  revealRadius?: number;
  color: string;
}

export const DEPLOYABLES: Record<DeployableKind, DeployableDef> = {
  barricade: {
    kind: 'barricade', name: 'Barricade',
    description: 'Cover that blocks bullets and movement. Rotate to angle it.',
    hp: 400, length: 96, width: 22, blocks: true, rotatable: true,
    teamLimit: 6, cooldownSec: 10, placeOffset: 50,
    color: '#8a7a56',
  },
  turret: {
    kind: 'turret', name: 'Sentry Gun',
    description: 'Tracks and fires on enemies in its line of sight.',
    hp: 220, length: 34, width: 34, blocks: true, rotatable: false,
    teamLimit: 2, cooldownSec: 35, placeOffset: 46,
    range: 620, rpm: 200, damage: 11, turnRate: 2.6, armingSec: 2,
    color: '#7f93b8',
  },
  mine: {
    kind: 'mine', name: 'Proximity Mine',
    description: 'Hidden charge. Wrecks vehicles; jump to clear one.',
    hp: 60, length: 24, width: 24, blocks: false, rotatable: false,
    teamLimit: 4, cooldownSec: 16, placeOffset: 36,
    armingSec: 1.5, triggerRadius: 30, revealRadius: 150,
    color: '#5f6b48',
  },
};

export const deployableDef = (kind: DeployableKind): DeployableDef =>
  DEPLOYABLES[kind];

// ---------------------------------------------------------------------------
// Pickups
// ---------------------------------------------------------------------------

export type PickupKind = 'weapon' | 'ammo' | 'health' | 'armor';

export interface PickupSpawnDef {
  id: string;
  x: number;
  y: number;
  kind: PickupKind;
  /** For weapon spawns: a fixed weapon, or undefined for a tier-weighted roll. */
  weapon?: WeaponId;
  /** Tier restriction for random weapon spawns. */
  tier?: WeaponTier;
  /** Seconds before this spawn point becomes active again after being taken. */
  respawnSec: number;
}

// ---------------------------------------------------------------------------
// Maps
// ---------------------------------------------------------------------------

export type ZoneKind =
  | 'road'
  | 'sidewalk'
  | 'downtown'
  | 'residential'
  | 'industrial'
  | 'park'
  | 'water'
  | 'base';

export interface ZoneDef {
  kind: ZoneKind;
  rect: Rect;
  /** Optional landmark label drawn on the expanded map. */
  label?: string;
  /** Team index for `base` zones. */
  team?: number;
}

export interface SolidDef {
  rect: Rect;
  /** Buildings render taller than props; both block movement and bullets. */
  kind: 'building' | 'prop' | 'wall';
  height?: number;
}

export interface TeamSpawnDef {
  team: number;
  zone: Rect;
}

export interface VehicleSpawnDef {
  x: number;
  y: number;
  rot: number;
  type: VehicleTypeId;
  respawnSec: number;
}

export type GameModeId = 'tdm' | 'ctf' | 'br';

export interface GameMapDef {
  id: string;
  name: string;
  width: number;
  height: number;
  tileSize: number;
  zones: ZoneDef[];
  solids: SolidDef[];
  teamSpawns: TeamSpawnDef[];
  vehicleSpawns: VehicleSpawnDef[];
  pickupSpawns: PickupSpawnDef[];
  /** Capture-the-flag bases, one per supported team. */
  flagBases: { team: number; x: number; y: number; captureRadius: number }[];
  /** Battle-royale final safe-zone centre and starting radius. */
  safeZone: { x: number; y: number; startRadius: number };
  modes: GameModeId[];
  recommendedPlayers: number;
  maxTeams: number;
}

// ---------------------------------------------------------------------------
// Match configuration and lifecycle
// ---------------------------------------------------------------------------

export type LoadoutRule =
  | 'fixed'
  | 'random-tier'
  | 'team-pool'
  | 'none'
  | 'chaos';

export interface MatchConfig {
  mapId: string;
  mode: GameModeId;
  teamCount: number;
  teamSize: number;
  /** Kills (tdm) or captures (ctf) needed to win. */
  scoreTarget: number;
  matchDurationSec: number;
  respawnDelaySec: number;
  loadoutRule: LoadoutRule;
  botsEnabled: boolean;
  botDifficulty: BotDifficulty;
  friendlyFire: boolean;
  vehiclesEnabled: boolean;
}

export type BotDifficulty = 'easy' | 'normal' | 'hard';

export type MatchPhase =
  | 'lobby'
  | 'loading'
  | 'countdown'
  | 'active'
  | 'concluded';

export type PlayerLifeState =
  | 'alive'
  | 'dead'
  | 'respawning'
  | 'spectating';

export type ConnectionState = 'connected' | 'reconnecting' | 'left';

export interface PlayerStats {
  kills: number;
  deaths: number;
  assists: number;
  objectiveScore: number;
  score: number;
  streak: number;
  bestStreak: number;
  damageDealt: number;
}

export const emptyStats = (): PlayerStats => ({
  kills: 0,
  deaths: 0,
  assists: 0,
  objectiveScore: 0,
  score: 0,
  streak: 0,
  bestStreak: 0,
  damageDealt: 0,
});

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

/** Bitmask of held buttons; keeps input packets tiny and easy to replay. */
export const Btn = {
  Up: 1 << 0,
  Down: 1 << 1,
  Left: 1 << 2,
  Right: 1 << 3,
  Fire: 1 << 4,
  Sprint: 1 << 5,
  Reload: 1 << 6,
  Interact: 1 << 7,
  Swap: 1 << 8,
  Jump: 1 << 9,
  UseMedkit: 1 << 10,
  UseArmor: 1 << 11,
} as const;

export interface InputCommand {
  /** Monotonic per-client sequence number, used for reconciliation. */
  seq: number;
  /** Simulated milliseconds this command covers (clamped by the server). */
  dtMs: number;
  buttons: number;
  /** Aim angle in radians, world space. */
  aim: number;
  /** Requested weapon slot, or -1 for no change. */
  slot: number;
  /**
   * Optional analog direction in world space, magnitude 0..1: where the player
   * wants to go. On foot it replaces the digital direction bits; a driver's
   * vehicle steers and throttles toward it. Keyboards leave it unset, so their
   * handling is exactly the digital path. The server clamps it to length 1, so
   * an analog stick can never outpace a keyboard.
   */
  ax?: number;
  ay?: number;
}
